### ISSUE TITLE
Post List Doesn't Update in Sync with Pagination

### ISSUE THREAD

**Issue by ahmadawais** [xwp/wp-customize-posts#124]
So, I went ahead installed the plugin from the W.org repo via WPCLI. The first test was to see if the list of pagination updates in sync with the list of pagination being displayed in the theme.

Somehow, this doesn't work well. Sometimes the sticky post sticks at the top, other times it doesn't. Check this image; there are 5 posts above the posts list being displayed in the theme, those five posts are not sticky.

![](https://i.imgur.com/yHgKfUo.png)

**Comment by westonruter** [comment]
@ahmadawais so the issue is that the list of post sections in the Customize pane appear in a different order than the posts appear in the preview?

Part of the issue I think is that the post settings are exported from the preview in an object (mapping ID to setting properties) as opposed to an array of settings: https://github.com/xwp/wp-customize-posts/blob/9ccc8f23a1589fc8098cac791c857781a605ef45/js/customize-posts.js#L59-L76

Objects in JavaScript are not ordered, so this could be part of the issue.

Another issue could be that the posts sections get added the to bottom of the list as they are encountered (e.g. infinite scroll or updating a Recent Posts widget to show more posts): https://github.com/xwp/wp-customize-posts/blob/9ccc8f23a1589fc8098cac791c857781a605ef45/js/customize-post-section.js#L68-L74

In regards to Sticky posts: it is also somewhat expected that these wouldn't be exported in the order displayed because the posts get re-ordered in `WP_Query`, but it seems the `the_posts` filter is applied after the stickies are re-ordered, so maybe that isn't the issue, and the settings get added by looking at `the_posts` filter: https://github.com/xwp/wp-customize-posts/blob/9ccc8f23a1589fc8098cac791c857781a605ef45/php/class-wp-customize-posts-preview.php#L127-L147

**Comment by ahmadawais** [comment]
I guess, it is not just limited to the order of posts. E.g. The first post being displayed in the image above i.e. `Hello FB Save Button for WP` that is the latest post and when I took this screenshot, I was on the third page of pagination while each page had 10 posts (the default behavior).

I can test it more and try to figure out a pattern.

**Comment by westonruter** [comment]
I think the pattern will end up being random at times due to the JS object not preserving the order.

**Comment by ahmadawais** [comment]
^You are right.
