### ISSUE TITLE
Improve handling of active state for dynamically-created controls/sections/panels

### ISSUE THREAD

**Issue by sayedwp** [xwp/wp-customize-posts#157]
When creating a dynamic control using `wp.customize.DynamicControl`, it does gives access to the methods that  are available in the default controls. So we cannot do `wp.customize.control( 'dynamicId' ).deactivate();` on these newly added controls.

Default control : 

![screen shot 2016-06-01 at 1 11 05 am](https://cloud.githubusercontent.com/assets/6297436/15744949/caff4a0c-28ec-11e6-872c-a3157c495881.png)

Dynamic Control : 

![screen shot 2016-06-01 at 1 12 56 am](https://cloud.githubusercontent.com/assets/6297436/15744942/c13ca62c-28ec-11e6-8629-7d2ffdfedbf2.png)

I am using the develop branch( Version: 0.5.0 ) of this plugin

**Comment by westonruter** [comment]
@sayedwp The `deactivate` method should be present. I just tried this and it doesn't error: 

```js
wp.customize.control('post[post][5779][post_excerpt]').deactivate()
```

But actually, there is no effect. The control does not hide. The reason for this is we override the `active.validate` method: https://github.com/xwp/wp-customize-posts/blob/d75de18d7f7b2cb882b7433933f7f29fb9640d38/js/customize-post-section.js#L662-L665

So this override would need to be removed or overridden. See also the custom logic for `validate` on the section itself, where it prevents the `active` state from going `false` if the setting is dirty: https://github.com/xwp/wp-customize-posts/blob/d75de18d7f7b2cb882b7433933f7f29fb9640d38/js/customize-post-section.js#L78-L85

**Comment by sayedwp** [comment]
okay I see, it was not working because of `active.validate` method. It was not visible in console, so I thought it's probably not available, thanks

**Comment by westonruter** [comment]
Yes, it's not exactly intuitive right now. An improvement is needed in core to prevent dynamically-added controls from being deactivated when the preview refreshes, to avoid us needing to add these `validate` overrides. 

The relevant code is right here: https://github.com/xwp/wordpress-develop/blob/230f2986fb744a9d0dcaa09a448f9982b26322d6/src/wp-admin/js/customize-controls.js#L2883-L2911

And the specific code causing the problem is:

```js
var active = !! ( activeConstructs && activeConstructs[ id ] );
```

We could potentially fix this in Core by something like:

```js
if ( ! activeConstructs ) {
    return;
}
var active, isDynamicallyCreated;
if ( ! _.isUndefined( activeConstructs[ id ] ) {
    active = _.isUndefined( activeConstructs[ id ];
} else {
    isDynamicallyCreated = ! _.isUndefined( wp.customize.settings[ type + 's' ][ id ] );
    active = isDynamicallyCreated ? null : false;
}
if ( _.isBoolean( active ) ) {
    if ( active ) {
        construct.activate();
    } else {
        construct.deactivate();
    }
}
```

The `isDynamicallyCreated` check prevents dynamically-created constructs from being deactivated from preview refreshes since the control wouldn't be shown in the preview. So if it was dynamically created, and it didn't exist when the preview refreshed, then the change to the active state would be eliminated. This would allow us to get rid of our `validate` overrides.

Could you give that a try and see if it works? We could get this into 4.6.

**Comment by westonruter** [comment]
Moved to Trac: https://core.trac.wordpress.org/ticket/37270
