### ISSUE TITLE
Change Featured Image on "Home"-View

### ISSUE THREAD

**Issue by websupporter** [xwp/wp-customize-posts#297]
If you open the customizer you are on the "Home"-View. You go to Posts and you select a post, which is visible in this view. You change the featured image and after the refresh, the featured image is shown. From the Posts you select another post also visible on the "Home"-View and you change the featured image, the featured image of the first post you've edited is going to be replaced in the preview.

If you hit "save &publish" the featured images are saved correctly.

**Comment by westonruter** [comment]
Good catch. The problem is that the selector for the featured image partial is not specific enough. It's only looking for elements that match the selector `[data-customize-featured-image-partial]`: https://github.com/xwp/wp-customize-posts/blob/f0821370cd567f87cc6d92d42727dbc0be803581/php/class-wp-customize-featured-image-controller.php#L96

Here is where the attribute is injected into the featured image element: https://github.com/xwp/wp-customize-posts/blob/f0821370cd567f87cc6d92d42727dbc0be803581/php/class-wp-customize-featured-image-controller.php#L322

```php
$replacement .= sprintf( ' %s="1" ', self::SELECTED_ATTRIBUTE );
```

This needs to be changed perhaps so that the post/page ID for the featured image is supplied instead of `1`. In this way, the featured image partial can target only the relevant placements.

We also may need to dynamically add the partials rather than declare them statically, since the selector is going to change for each.
