### ISSUE TITLE
Expanded editor overlays expand button for collapsed Customizer pane

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-posts#44]
If the editor is expanded and the collapse link for the Customizer pane is clicked, the pane will slide away but the button to re-expand the panel will be _behind_ the editor and so the user will be stuck.

**Comment by westonruter** [comment]
This is closely related to https://core.trac.wordpress.org/ticket/36678

There should be a state for whether the Customize pane is expanded and the editor should collapse whenever this state changes to collapsed.

**Comment by westonruter** [comment]
Or, as @stuartshields notes, they may want the editor visible with the pane collapsed for more real estate. So the expand button may just need a higher z-index.

**Comment by valendesigns** [comment]
Or it could be moved up 300px to come into view and then a higher z-index in fullscreen mode.

**Comment by stuartshields** [comment]
@valendesigns I've done a quick concept of just adding the z-index in, I agree with you, we'd need to move it up by 300px otherwise it'll get lost if the user has a screenshot/video in the post. See below of it in a normal post.

<img width="246" alt="screen shot 2016-04-30 at 7 41 55 am" src="https://cloud.githubusercontent.com/assets/15369210/14930411/18d3c07e-0ea7-11e6-8a05-6fbd065e804d.png">

**Comment by valendesigns** [comment]
@stuartshields Yes, that would be very confusing in that placement. However, in fullscreen mode it would probably be OK to keep it there.

**Comment by stuartshields** [comment]
@valendesigns This was pretty simple to do with CSS. Here is the branch - https://github.com/xwp/wp-customize-posts/tree/bugfix%2F44-expanded-editor-overlay

**Comment by valendesigns** [comment]
Awesome, thanks. I'll review it later tonight.
